# Generated by Django 4.2.6 on 2023-10-24 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_thing_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, max_length=120, validators=[django.core.validators.RegexValidator(message='Description can have up to 120 characters', regex='^.{0,120}$')]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be unique, not blank, and have no more than 30 characters', regex='^\\w{1,30}$')]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Quantity cannot be more than 100'), django.core.validators.MinValueValidator(0, message='Quantity cannot be less than 0')]),
        ),
    ]
